- name: Install and configure nomad servers with consul servers
  hosts: servers
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: consul-server
   - role: nomad-server
